### ISSUE TITLE
你好:)

### ISSUE THREAD

**Issue by leetking** [tobepro/doubanfm-gtk#1]
我现在正在学习gtk和网络方面的东西，你的这个东西还在更新没有呢？今天发现这个东西很激动，想把这个东西做好一些:P

**Comment by tobepro** [comment]
我gtk也没看多少,只是为了手机做的一个简单demo,豆瓣的音乐不太全,我准备把网易云音乐的api爬下来做成gtk的客户端,有兴趣的话可以关注我的其他项目

**Comment by leetking** [comment]
对了，您可不可以留下您的邮箱呢，我可以向您请教写问题。关于如何分析网页api的问题

**Comment by tobepro** [comment]
tobeprogramer@gmail.com
